name: C++ CI

on: push

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      env:
        dependency_packages: build-essential g++-5
      run: sudo apt-get update && sudo apt-get -y install ${dependency_packages}

    - name: Build
      run: |
        mkdir -p build && cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        cmake --build . --config $BUILD_TYPE -j4

    - name: Test
      run: ctest -C $BUILD_TYPE -V
